---
AWSTemplateFormatVersion: 2010-09-09

Description: Stack to deploy a WordPress environment based on https://github.com/aws-samples/aws-refarch-wordpress.

MetaData:
  Authors:
    Description: Darryl Osborne (darrylo@amazon.com)  modified by K247work.
